(function() {

	var catas = {
		cata1: {
			header: {
				"index1": {
					"title": "女装",
					"href": "http://www.taobao.com/market/nvzhuang/index.php"
				},
				"index2": {
					"title": "男装",
					"href": "http://www.taobao.com/market/nanzhuang/index.php"
				},
				"index3": {
					"title": "年度TOP热卖羽绒",
					"href": "http://www.taobao.com/market/nvzhuang/rmyr.php"
				},
				"index4": {
					"title": "风格尚新",
					"href": "http://www.taobao.com/market/nvzhuang/aqfenge.php"
				},
				"index5": {
					"title": "毛呢大衣",
					"href": "http://www.taobao.com/market/nanzhuang/mndy2014.php"
				}
			},
			type1: [{
				"title": "潮流女装",
				"href": "http://www.taobao.com/market/nvzhuang/index.php",
				"class": "item-header"
			}, {
				"title": "冬上新",
				"href": "http://www.taobao.com/market/nvzhuang/xinpin.php",
				"class": ""
			}, {
				"title": "韩版",
				"href": "http://www.taobao.com/market/nvzhuang/sweet.php",
				"class": ""
			}, {
				"title": "连衣裙",
				"href": "http://www.taobao.com/market/nvzhuang/dress.php",
				"class": ""
			}, {
				"title": "套装裙",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "大码MM",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "羽绒服",
				"href": "http://www.taobao.com/market/nvzhuang/yurong.php",
				"class": "item-header"
			}, {
				"title": "短羽绒",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "奢华毛领",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "棉服",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "皮草",
				"href": "http://www.taobao.com/market/nvzhuang/piyipicaopingdao.php",
				"class": ""
			}, {
				"title": "外套",
				"href": "http://www.taobao.com/market/nvzhuang/qiuwaitao.php",
				"class": ""
			}, {
				"title": "毛呢大衣",
				"href": "http://www.taobao.com/market/nvzhuang/maoni.php",
				"class": "item-header"
			}, {
				"title": "中长款",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "羊绒大衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "卫衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "皮衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "衬衫",
				"href": "http://www.taobao.com/market/nvzhuang/shirt.php",
				"class": ""
			}, {
				"title": "毛衣针织",
				"href": "http://www.taobao.com/market/nvzhuang/maoyi.php",
				"class": "item-header"
			}, {
				"title": "羊绒衫",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "裤子",
				"href": "http://www.taobao.com/market/nvzhuang/trousers.php",
				"class": ""
			}, {
				"title": "加绒裤",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "打底裤",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "内衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}],
			type2: [{
				"title": "精选男装",
				"href": "http://www.taobao.com/market/nanzhuang/index.php",
				"class": "item-header"
			}, {
				"title": "冬上新",
				"href": "http://www.taobao.com/market/nanzhuang/xinpin.php",
				"class": ""
			}, {
				"title": "潮流",
				"href": "http://www.taobao.com/market/nanzhuang/citiao/nanchao.php",
				"class": ""
			}, {
				"title": "时尚",
				"href": "http://www.taobao.com/market/nanzhuang/shishang.php",
				"class": ""
			}, {
				"title": "商务",
				"href": "http://www.taobao.com/market/nanzhuang/swss.php",
				"class": ""
			}, {
				"title": "保暖棉衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "冬季外套",
				"href": "http://s.taobao.com/list",
				"class": "item-header"
			}, {
				"title": "毛呢",
				"href": "http://www.taobao.com/market/nanzhuang/mndy2014.php",
				"class": ""
			}, {
				"title": "毛衣",
				"href": "http://www.taobao.com/market/nanzhuang/citiao/maoyi.php",
				"class": ""
			}, {
				"title": "夹克",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "皮衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "卫衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "西服",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "羽绒服",
				"href": "http://www.taobao.com/market/nanzhuang/citiao/yurongfu.php",
				"class": "item-header"
			}, {
				"title": "牛仔裤",
				"href": "http://www.taobao.com/market/nanzhuang/citiao/kuzhuang.php",
				"class": ""
			}, {
				"title": "休闲裤",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "衬衫",
				"href": "http://www.taobao.com/market/nanzhuang/citiao/chenshan.php",
				"class": ""
			}, {
				"title": "风衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "针织衫",
				"href": "http://s.taobao.com/list",
				"class": ""
			}],
			type3: [{
				"title": "潮流男装",
				"href": "http://s.taobao.com/list",
				"class": "guess"
			}, {
				"title": "羽绒服",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "卫衣",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "内裤",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "女装精品",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "打底裙",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "毛呢外套",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "打底衫",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "冬装",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "毛针织衫",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}]
		},
		cata2: {
			header: {
				"index1": {
					"title": "鞋靴",
					"href": "http://xie.taobao.com/",
					"class": ""
				},
				"index2": {
					"title": "箱包",
					"href": "http://www.taobao.com/market/nvbao/shouye.php",
					"class": ""
				},
				"index3": {
					"title": "过年穿新鞋",
					"href": "http://www.taobao.com/market/nvxie/citiao/index.php",
					"class": ""
				},
				"index4": {
					"title": "品牌男鞋",
					"href": "http://www.taobao.com/market/nanxie/citiao/index.php",
					"class": ""
				},
				"index5": {
					"title": "潮包推荐",
					"href": "http://www.taobao.com/market/nanbao/shouye.php",
					"class": ""
				}
			},
			type1: [{
				"title": "女鞋",
				"href": "http://www.taobao.com/market/nvxie/citiao/index.php",
				"class": "item-header"
			}, {
				"title": "冬新款",
				"href": "http://www.taobao.com/market/nvxie/xinpin.php",
				"class": "em"
			}, {
				"title": "靴子",
				"href": "http://www.taobao.com/market/nvxie/xuezi.php",
				"class": ""
			}, {
				"title": "高帮",
				"href": "http://www.taobao.com/market/nvxie/gaobangnvxie.php",
				"class": ""
			}, {
				"title": "帆布鞋",
				"href": "http://www.taobao.com/market/nvxie/citiao/fanbuxie.php",
				"class": ""
			}, {
				"title": "真皮女鞋",
				"href": "http://www.taobao.com/market/nvxie/zhengpi.php",
				"class": "em"
			}, {
				"title": "短靴",
				"href": "http://s.taobao.com/list",
				"class": "item-header"
			}, {
				"title": "雪地靴",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "平跟",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "中跟",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "高跟",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "坡跟",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "单鞋",
				"href": "http://www.taobao.com/market/nvxie/citiao/danxie.php",
				"class": ""
			}, {
				"title": "男鞋",
				"href": "http://www.taobao.com/market/nanxie/citiao/index.php",
				"class": "item-header"
			}, {
				"title": "休闲",
				"href": "http://www.taobao.com/market/nanxie/citiao/xiuxian.php",
				"class": ""
			}, {
				"title": "商务",
				"href": "http://www.taobao.com/market/nanxie/citiao/shangwu.php",
				"class": ""
			}, {
				"title": "潮流",
				"href": "http://www.taobao.com/market/nanxie/citiao/chaoliu.php",
				"class": ""
			}, {
				"title": "马丁靴",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "高帮鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "加绒保暖",
				"href": "http://s.taobao.com/list",
				"class": "item-header"
			}, {
				"title": "品牌折扣",
				"href": "http://www.taobao.com/market/nvxie/citiao/pinpai.php",
				"class": "em"
			}, {
				"title": "爸妈鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "棉鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "低帮",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "豆豆鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}],
			type2: [{
				"title": "女包",
				"href": "http://www.taobao.com/market/nvbao/shouye.php",
				"class": "item-header"
			}, {
				"title": "冬新款",
				"href": "http://www.taobao.com/market/nvbao/new2.php",
				"class": "em"
			}, {
				"title": "手提包",
				"href": "http://www.taobao.com/market/nvbao/stb.php",
				"class": ""
			}, {
				"title": "斜挎包",
				"href": "http://www.taobao.com/market/nvbao/citiao/xkb.php",
				"class": ""
			}, {
				"title": "大牌",
				"href": "http://www.taobao.com/market/nvbao/dapaixiangbao.php",
				"class": ""
			}, {
				"title": "真皮",
				"href": "http://www.taobao.com/market/nvbao/citiao/zhenpi.php",
				"class": ""
			}, {
				"title": "男包",
				"href": "http://www.taobao.com/market/nanbao/shouye.php",
				"class": "item-header"
			}, {
				"title": "潮包",
				"href": "http://www.taobao.com/market/nanbao/citiao/cl.php",
				"class": "em"
			}, {
				"title": "商务包",
				"href": "http://www.taobao.com/market/nanbao/citiao/sw.php",
				"class": ""
			}, {
				"title": "双肩包",
				"href": "http://www.taobao.com/market/nvbao/shuangjianbao.php",
				"class": ""
			}, {
				"title": "拉杆箱",
				"href": "http://www.taobao.com/market/nvbao/lvxingxiang.php",
				"class": ""
			}, {
				"title": "钱包",
				"href": "http://www.taobao.com/market/nvbao/citiao/qianbao2.php",
				"class": ""
			}, {
				"title": "服饰配件",
				"href": "http://www.taobao.com/market/fspj/index.php",
				"class": "item-header"
			}, {
				"title": "围巾",
				"href": "http://www.taobao.com/market/fspj/sjg.php",
				"class": ""
			}, {
				"title": "帽子",
				"href": "http://www.taobao.com/market/fspj/mzg.php",
				"class": ""
			}, {
				"title": "皮带",
				"href": "http://www.taobao.com/market/fspj/yaodai.php",
				"class": ""
			}, {
				"title": "手套",
				"href": "http://www.taobao.com/market/fspj/shoutao.php",
				"class": "em"
			}, {
				"title": "围脖",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "毛领",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, ],
			type3: [{
				"title": "热销男包",
				"href": "http://s.taobao.com/list",
				"class": "guess"
			}, {
				"title": "拉杆箱",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "凉鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "帽子",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "新品女靴",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "包包",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "运动鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "丝巾",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "皮鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, ]
		},
		cata3: {},
		cata4: {},
		cata5: {},
		cata6: {}
	};
	define(function() {
		var data = {
			catas: catas
		};
		return data;
	});
})();