(function() {

	var catas = {
		cata1: {
			header: {
				"index1": {
					"title": "女装",
					"href": "http://www.taobao.com/market/nvzhuang/index.php"
				},
				"index2": {
					"title": "男装",
					"href": "http://www.taobao.com/market/nanzhuang/index.php"
				},
				"index3": {
					"title": "年度TOP热卖羽绒",
					"href": "http://www.taobao.com/market/nvzhuang/rmyr.php"
				},
				"index4": {
					"title": "风格尚新",
					"href": "http://www.taobao.com/market/nvzhuang/aqfenge.php"
				},
				"index5": {
					"title": "毛呢大衣",
					"href": "http://www.taobao.com/market/nanzhuang/mndy2014.php"
				}
			},
			type1: [{
				"title": "潮流女装",
				"href": "http://www.taobao.com/market/nvzhuang/index.php",
				"class": "item-header"
			}, {
				"title": "冬上新",
				"href": "http://www.taobao.com/market/nvzhuang/xinpin.php",
				"class": ""
			}, {
				"title": "韩版",
				"href": "http://www.taobao.com/market/nvzhuang/sweet.php",
				"class": ""
			}, {
				"title": "连衣裙",
				"href": "http://www.taobao.com/market/nvzhuang/dress.php",
				"class": ""
			}, {
				"title": "套装裙",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "大码MM",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "羽绒服",
				"href": "http://www.taobao.com/market/nvzhuang/yurong.php",
				"class": "item-header"
			}, {
				"title": "短羽绒",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "奢华毛领",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "棉服",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "皮草",
				"href": "http://www.taobao.com/market/nvzhuang/piyipicaopingdao.php",
				"class": ""
			}, {
				"title": "外套",
				"href": "http://www.taobao.com/market/nvzhuang/qiuwaitao.php",
				"class": ""
			}, {
				"title": "毛呢大衣",
				"href": "http://www.taobao.com/market/nvzhuang/maoni.php",
				"class": "item-header"
			}, {
				"title": "中长款",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "羊绒大衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "卫衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "皮衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "衬衫",
				"href": "http://www.taobao.com/market/nvzhuang/shirt.php",
				"class": ""
			}, {
				"title": "毛衣针织",
				"href": "http://www.taobao.com/market/nvzhuang/maoyi.php",
				"class": "item-header"
			}, {
				"title": "羊绒衫",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "裤子",
				"href": "http://www.taobao.com/market/nvzhuang/trousers.php",
				"class": ""
			}, {
				"title": "加绒裤",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "打底裤",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "内衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}],
			type2: [{
				"title": "精选男装",
				"href": "http://www.taobao.com/market/nanzhuang/index.php",
				"class": "item-header"
			}, {
				"title": "冬上新",
				"href": "http://www.taobao.com/market/nanzhuang/xinpin.php",
				"class": ""
			}, {
				"title": "潮流",
				"href": "http://www.taobao.com/market/nanzhuang/citiao/nanchao.php",
				"class": ""
			}, {
				"title": "时尚",
				"href": "http://www.taobao.com/market/nanzhuang/shishang.php",
				"class": ""
			}, {
				"title": "商务",
				"href": "http://www.taobao.com/market/nanzhuang/swss.php",
				"class": ""
			}, {
				"title": "保暖棉衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "冬季外套",
				"href": "http://s.taobao.com/list",
				"class": "item-header"
			}, {
				"title": "毛呢",
				"href": "http://www.taobao.com/market/nanzhuang/mndy2014.php",
				"class": ""
			}, {
				"title": "毛衣",
				"href": "http://www.taobao.com/market/nanzhuang/citiao/maoyi.php",
				"class": ""
			}, {
				"title": "夹克",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "皮衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "卫衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "西服",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "羽绒服",
				"href": "http://www.taobao.com/market/nanzhuang/citiao/yurongfu.php",
				"class": "item-header"
			}, {
				"title": "牛仔裤",
				"href": "http://www.taobao.com/market/nanzhuang/citiao/kuzhuang.php",
				"class": ""
			}, {
				"title": "休闲裤",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "衬衫",
				"href": "http://www.taobao.com/market/nanzhuang/citiao/chenshan.php",
				"class": ""
			}, {
				"title": "风衣",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "针织衫",
				"href": "http://s.taobao.com/list",
				"class": ""
			}],
			type3: [{
				"title": "潮流男装",
				"href": "http://s.taobao.com/list",
				"class": "guess"
			}, {
				"title": "羽绒服",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "卫衣",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "内裤",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "女装精品",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "打底裙",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "毛呢外套",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "打底衫",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "冬装",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "毛针织衫",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}]
		},
		cata2: {
			header: {
				"index1": {
					"title": "鞋靴",
					"href": "http://xie.taobao.com/",
					"class": ""
				},
				"index2": {
					"title": "箱包",
					"href": "http://www.taobao.com/market/nvbao/shouye.php",
					"class": ""
				},
				"index3": {
					"title": "过年穿新鞋",
					"href": "http://www.taobao.com/market/nvxie/citiao/index.php",
					"class": ""
				},
				"index4": {
					"title": "品牌男鞋",
					"href": "http://www.taobao.com/market/nanxie/citiao/index.php",
					"class": ""
				},
				"index5": {
					"title": "潮包推荐",
					"href": "http://www.taobao.com/market/nanbao/shouye.php",
					"class": ""
				}
			},
			type1: [{
				"title": "女鞋",
				"href": "http://www.taobao.com/market/nvxie/citiao/index.php",
				"class": "item-header"
			}, {
				"title": "冬新款",
				"href": "http://www.taobao.com/market/nvxie/xinpin.php",
				"class": "em"
			}, {
				"title": "靴子",
				"href": "http://www.taobao.com/market/nvxie/xuezi.php",
				"class": ""
			}, {
				"title": "高帮",
				"href": "http://www.taobao.com/market/nvxie/gaobangnvxie.php",
				"class": ""
			}, {
				"title": "帆布鞋",
				"href": "http://www.taobao.com/market/nvxie/citiao/fanbuxie.php",
				"class": ""
			}, {
				"title": "真皮女鞋",
				"href": "http://www.taobao.com/market/nvxie/zhengpi.php",
				"class": "em"
			}, {
				"title": "短靴",
				"href": "http://s.taobao.com/list",
				"class": "item-header"
			}, {
				"title": "雪地靴",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "平跟",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "中跟",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "高跟",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "坡跟",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "单鞋",
				"href": "http://www.taobao.com/market/nvxie/citiao/danxie.php",
				"class": ""
			}, {
				"title": "男鞋",
				"href": "http://www.taobao.com/market/nanxie/citiao/index.php",
				"class": "item-header"
			}, {
				"title": "休闲",
				"href": "http://www.taobao.com/market/nanxie/citiao/xiuxian.php",
				"class": ""
			}, {
				"title": "商务",
				"href": "http://www.taobao.com/market/nanxie/citiao/shangwu.php",
				"class": ""
			}, {
				"title": "潮流",
				"href": "http://www.taobao.com/market/nanxie/citiao/chaoliu.php",
				"class": ""
			}, {
				"title": "马丁靴",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "高帮鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "加绒保暖",
				"href": "http://s.taobao.com/list",
				"class": "item-header"
			}, {
				"title": "品牌折扣",
				"href": "http://www.taobao.com/market/nvxie/citiao/pinpai.php",
				"class": "em"
			}, {
				"title": "爸妈鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "棉鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "低帮",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "豆豆鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}],
			type2: [{
				"title": "女包",
				"href": "http://www.taobao.com/market/nvbao/shouye.php",
				"class": "item-header"
			}, {
				"title": "冬新款",
				"href": "http://www.taobao.com/market/nvbao/new2.php",
				"class": "em"
			}, {
				"title": "手提包",
				"href": "http://www.taobao.com/market/nvbao/stb.php",
				"class": ""
			}, {
				"title": "斜挎包",
				"href": "http://www.taobao.com/market/nvbao/citiao/xkb.php",
				"class": ""
			}, {
				"title": "大牌",
				"href": "http://www.taobao.com/market/nvbao/dapaixiangbao.php",
				"class": ""
			}, {
				"title": "真皮",
				"href": "http://www.taobao.com/market/nvbao/citiao/zhenpi.php",
				"class": ""
			}, {
				"title": "男包",
				"href": "http://www.taobao.com/market/nanbao/shouye.php",
				"class": "item-header"
			}, {
				"title": "潮包",
				"href": "http://www.taobao.com/market/nanbao/citiao/cl.php",
				"class": "em"
			}, {
				"title": "商务包",
				"href": "http://www.taobao.com/market/nanbao/citiao/sw.php",
				"class": ""
			}, {
				"title": "双肩包",
				"href": "http://www.taobao.com/market/nvbao/shuangjianbao.php",
				"class": ""
			}, {
				"title": "拉杆箱",
				"href": "http://www.taobao.com/market/nvbao/lvxingxiang.php",
				"class": ""
			}, {
				"title": "钱包",
				"href": "http://www.taobao.com/market/nvbao/citiao/qianbao2.php",
				"class": ""
			}, {
				"title": "服饰配件",
				"href": "http://www.taobao.com/market/fspj/index.php",
				"class": "item-header"
			}, {
				"title": "围巾",
				"href": "http://www.taobao.com/market/fspj/sjg.php",
				"class": ""
			}, {
				"title": "帽子",
				"href": "http://www.taobao.com/market/fspj/mzg.php",
				"class": ""
			}, {
				"title": "皮带",
				"href": "http://www.taobao.com/market/fspj/yaodai.php",
				"class": ""
			}, {
				"title": "手套",
				"href": "http://www.taobao.com/market/fspj/shoutao.php",
				"class": "em"
			}, {
				"title": "围脖",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "毛领",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, ],
			type3: [{
				"title": "热销男包",
				"href": "http://s.taobao.com/list",
				"class": "guess"
			}, {
				"title": "拉杆箱",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "凉鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "帽子",
				"href": "http://s.taobao.com/list",
				"class": "em"
			}, {
				"title": "新品女靴",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "包包",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "运动鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "丝巾",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, {
				"title": "皮鞋",
				"href": "http://s.taobao.com/list",
				"class": ""
			}, ]
		},
		cata3: {"header":{"index1":{"title":"运动户外","href":"http://www.taobao.com/market/sport/citiao/yundongpai.php","class":""},"index2":{"title":"跟着达人买好货","href":"http://www.taobao.com/market/sport/citiao/yundongpai.php","class":""},"index3":{"title":"限量球鞋","href":"http://www.taobao.com/market/sport/sneaker.php","class":""},"index4":{"title":"户外探险","href":"http://www.taobao.com/market/huwai/citiao/huwaijianshen.php","class":""}},"type1":[{"title":"运动鞋","href":"http://www.taobao.com/market/sport/citiao/yundongxietest.php","class":"em"},{"title":"跑步鞋","href":"http://www.taobao.com/market/sport/citiao/paobuxie.php","class":""},{"title":"板鞋","href":"http://www.taobao.com/market/sport/citiao/banxie.php","class":""},{"title":"篮球鞋","href":"http://www.taobao.com/market/sport/citiao/lanqiuxie.php","class":""},{"title":"限量版","href":"http://www.taobao.com/market/sport/sneaker.php","class":""},{"title":"NB","href":"http://s.taobao.com/list","class":"em"},{"title":"运动服","href":"http://www.taobao.com/market/sport/citiao/yundongfu.php","class":""},{"title":"运动套装","href":"http://www.taobao.com/market/sport/citiao/yundongtaozhuang.php","class":""},{"title":"运动裤","href":"http://s.taobao.com/list","class":""},{"title":"羽绒服","href":"http://s.taobao.com/list","class":"em"},{"title":"冲锋衣","href":"http://www.taobao.com/market/huwai/citiao/chongfengyi.php","class":""},{"title":"户外运动","href":"http://www.taobao.com/market/huwai/citiao/huwaijianshen.php","class":""},{"title":"登山鞋","href":"http://www.taobao.com/market/huwai/citiao/yeying.php","class":""},{"title":"登山包","href":"http://s.taobao.com/list","class":""},{"title":"睡袋","href":"http://s.taobao.com/list","class":""},{"title":"钓竿","href":"http://s.taobao.com/list","class":""},{"title":"渔具","href":"http://www.taobao.com/market/huwai/citiao/diaogan.php","class":"em"},{"title":"健身用品","href":"http://www.taobao.com/market/huwai/go2gym.php","class":""},{"title":"广场舞","href":"http://www.taobao.com/market/sport/dance.php","class":"em"},{"title":"跑步机","href":"http://s.taobao.com/list","class":""},{"title":"甩脂机","href":"http://s.taobao.com/list","class":""},{"title":"哑铃","href":"http://s.taobao.com/list","class":""},{"title":"溜冰鞋","href":"http://s.taobao.com/list","class":""},{"title":"骑行装备","href":"http://www.taobao.com/market/huwai/citiao/qixing.php","class":""},{"title":"山地车","href":"http://www.taobao.com/market/huwai/citiao/shandiche.php","class":""},{"title":"折叠车","href":"http://s.taobao.com/list","class":""},{"title":"死飞","href":"http://s.taobao.com/list","class":"em"},{"title":"配件","href":"http://s.taobao.com/list","class":""},{"title":"装备","href":"http://s.taobao.com/list","class":""}],"type2":[],"type3":[{"title":"运动健身","href":"http://s.taobao.com/list","class":"guess "},{"title":"电动车","href":"http://s.taobao.com/list","class":"em"},{"title":"自行车","href":"http://s.taobao.com/list","class":""},{"title":"充电器","href":"http://s.taobao.com/list","class":""},{"title":"运动休闲","href":"http://s.taobao.com/list","class":""},{"title":"跑鞋","href":"http://s.taobao.com/list","class":"em"},{"title":"板鞋","href":"http://s.taobao.com/list","class":""},{"title":"男鞋","href":"http://s.taobao.com/list","class":""},{"title":"女子冲锋衣","href":"http://s.taobao.com/list","class":""},{"title":"运动长裤","href":"http://s.taobao.com/list","class":""}]},
		cata4: {"header":{"index1":{"title":"珠宝配饰","href":"http://www.taobao.com/market/peishi/peishi.php","class":""},"index2":{"title":"羊年转运饰品精选","href":"http://www.taobao.com/market/peishi/sytqsy.php","class":""},"index3":{"title":"手工银","href":"http://www.taobao.com/market/peishi/sytqsy.php","class":""},"index4":{"title":"海外名表","href":"http://www.taobao.com/market/peishi/sytqsy.php","class":""}},"type1":[{"title":"时尚饰品","href":"http://www.taobao.com/market/peishi/zmsp.php","class":""},{"title":"项链","href":"http://www.taobao.com/market/peishi/zmsp.php","class":""},{"title":"手链","href":"http://s.taobao.com/list","class":""},{"title":"戒指","href":"http://s.taobao.com/list","class":""},{"title":"发饰","href":"http://s.taobao.com/list","class":""},{"title":"银饰","href":"http://s.taobao.com/list","class":""},{"title":"水晶","href":"http://s.taobao.com/list","class":""},{"title":"珠宝首饰","href":"http://www.taobao.com/market/peishi/zhubao.php","class":"em"},{"title":"翡翠","href":"http://s.taobao.com/list","class":""},{"title":"彩宝","href":"http://s.taobao.com/list","class":""},{"title":"蜜蜡","href":"http://s.taobao.com/list","class":""},{"title":"裸钻","href":"http://s.taobao.com/list","class":""},{"title":"手镯","href":"http://s.taobao.com/list","class":""},{"title":"黄金","href":"http://s.taobao.com/list","class":""},{"title":"品质手表","href":"http://www.taobao.com/market/peishi/shoubiao.php","class":""},{"title":"瑞士表","href":"http://s.taobao.com/list","class":""},{"title":"机械表","href":"http://s.taobao.com/list","class":""},{"title":"时装表","href":"http://s.taobao.com/list","class":""},{"title":"情侣表","href":"http://s.taobao.com/list","class":""},{"title":"配件","href":"http://s.taobao.com/list","class":""},{"title":"眼镜配饰","href":"http://www.taobao.com/market/peishi/yanjing.php","class":""},{"title":"太阳镜","href":"http://s.taobao.com/list","class":""},{"title":"运动镜","href":"http://s.taobao.com/list","class":""},{"title":"光学镜","href":"http://s.taobao.com/list","class":""},{"title":"配件","href":"http://s.taobao.com/list","class":""},{"title":"zippo","href":"http://s.taobao.com/list","class":""},{"title":"瑞士军刀","href":"http://s.taobao.com/list","class":""},{"title":"最热单品","href":"http://www.taobao.com/market/peishi/peishi.php","class":""},{"title":"银饰","href":"http://s.taobao.com/list","class":"em"},{"title":"翡翠","href":"http://s.taobao.com/list","class":""},{"title":"水晶/佛珠","href":"http://s.taobao.com/list","class":""},{"title":"黄金","href":"http://s.taobao.com/list","class":""},{"title":"手表","href":"http://s.taobao.com/list","class":""},{"title":"眼镜","href":"http://s.taobao.com/list","class":""}],"type2":[],"type3":[{"title":"流行饰品","href":"http://s.taobao.com/list","class":"guess "},{"title":"头饰","href":"http://s.taobao.com/list","class":"em"},{"title":"手表","href":"http://s.taobao.com/list","class":""},{"title":"毛衣链","href":"http://s.taobao.com/list","class":""},{"title":"菩提","href":"http://s.taobao.com/list","class":""},{"title":"散珠","href":"http://s.taobao.com/list","class":""},{"title":"耳钉","href":"http://s.taobao.com/list","class":""},{"title":"耳环","href":"http://s.taobao.com/list","class":"em"},{"title":"情侣戒指","href":"http://s.taobao.com/list","class":""},{"title":"银手镯","href":"http://s.taobao.com/list","class":""}]} ,
		cata5: {"header":{"index1":{"title":"手机数码","href":"http://www.taobao.com/market/3c/home.php","class":""},"index2":{"title":"玩儿的就是想不到","href":"http://cdj.taobao.com/","class":""},"index3":{"title":"手机回收","href":"http://2.taobao.com/recycle/3c/","class":""},"index4":{"title":"4K显示器","href":"http://s.taobao.com/search","class":""}},"type1":[{"title":"手机","href":"http://www.taobao.com/market/3c/shouji.php","class":"em"},{"title":"iPhone","href":"http://s.taobao.com/list","class":"em"},{"title":"小米","href":"http://s.taobao.com/list","class":""},{"title":"华为","href":"http://s.taobao.com/list","class":""},{"title":"大神","href":"http://s.taobao.com/list","class":""},{"title":"魅族","href":"http://s.taobao.com/list","class":""},{"title":"三星","href":"http://s.taobao.com/list","class":""},{"title":"平板","href":"http://s.taobao.com/list","class":""},{"title":"iPad","href":"http://s.taobao.com/list","class":"em"},{"title":"小米","href":"http://s.taobao.com/list","class":""},{"title":"三星","href":"http://s.taobao.com/list","class":""},{"title":"10寸","href":"http://list.taobao.com/itemlist/shuma.htm","class":""},{"title":"台电","href":"http://s.taobao.com/list","class":""},{"title":"win8","href":"http://s.taobao.com/list","class":""},{"title":"电脑","href":"http://www.taobao.com/market/3c/diannao.php","class":""},{"title":"苹果","href":"http://s.taobao.com/list","class":""},{"title":"联想","href":"http://s.taobao.com/list","class":""},{"title":"外星人","href":"http://s.taobao.com/list","class":"em"},{"title":"台式机","href":"http://s.taobao.com/list","class":""},{"title":"路由器","href":"http://s.taobao.com/search","class":""},{"title":"学生","href":"http://s.taobao.com/list","class":""},{"title":"相机","href":"http://www.taobao.com/market/3c/360camera.php","class":""},{"title":"单反","href":"http://s.taobao.com/list","class":""},{"title":"自拍神器","href":"http://s.taobao.com/list","class":"em"},{"title":"拍立得","href":"http://s.taobao.com/list","class":""},{"title":"佳能","href":"http://s.taobao.com/list","class":""},{"title":"微单","href":"http://s.taobao.com/list","class":""},{"title":"镜头","href":"http://s.taobao.com/list","class":""},{"title":"3C配件","href":"http://www.taobao.com/market/3c/3cpeijian.php","class":""},{"title":"充电宝","href":"http://s.taobao.com/list","class":""},{"title":"智能穿戴","href":"http://s.taobao.com/list","class":"em"},{"title":"蓝牙耳机","href":"http://s.taobao.com/list","class":""},{"title":"暖手宝","href":"http://s.taobao.com/list","class":""},{"title":"电脑包","href":"http://s.taobao.com/list","class":""}],"type2":[],"type3":[{"title":"数码配件","href":"http://s.taobao.com/list","class":"guess "},{"title":"手机热销","href":"http://s.taobao.com/list","class":""},{"title":"手机壳","href":"http://s.taobao.com/list","class":"em"},{"title":"苹果保护套","href":"http://s.taobao.com/list","class":""},{"title":"移动电源","href":"http://s.taobao.com/list","class":""},{"title":"贴膜","href":"http://s.taobao.com/list","class":""},{"title":"手机膜","href":"http://s.taobao.com/list","class":""},{"title":"耳机","href":"http://s.taobao.com/list","class":""},{"title":"平板电脑","href":"http://s.taobao.com/list","class":""},{"title":"总成","href":"http://s.taobao.com/list","class":""}]} ,
		cata6: {"header":{"index1":{"title":"家电办公","href":"http://www.taobao.com/market/jiadian/home.php","class":""},"index2":{"title":"潮流电器","href":"http://cdj.taobao.com/","class":""},"index3":{"title":"年终精选","href":"http://www.taobao.com/market/jiadian/home.php","class":""},"index4":{"title":"暖冬特惠","href":"http://www.taobao.com/market/jiadian/home.php","class":""}},"type1":[{"title":"大家电","href":"http://www.taobao.com/market/jiadian/djd.php","class":""},{"title":"平板电视","href":"http://s.taobao.com/list","class":"em"},{"title":"油烟机","href":"http://s.taobao.com/list","class":""},{"title":"洗衣机","href":"http://s.taobao.com/list","class":""},{"title":"热水器","href":"http://s.taobao.com/search","class":""},{"title":"厨房电器","href":"http://www.taobao.com/market/jiadian/chufang.php","class":"em"},{"title":"榨汁机","href":"http://www.taobao.com/market/jiadian/ghceshi.php","class":""},{"title":"家用净水","href":"http://s.taobao.com/list","class":"em"},{"title":"电饭煲","href":"http://s.taobao.com/list","class":""},{"title":"豆浆机","href":"http://s.taobao.com/list","class":""},{"title":"面包机","href":"http://s.taobao.com/list","class":""},{"title":"电磁炉","href":"http://s.taobao.com/list","class":""},{"title":"生活电器","href":"http://www.taobao.com/market/jiadian/shenghuo.php","class":""},{"title":"加湿器","href":"http://s.taobao.com/list","class":""},{"title":"空气净化","href":"http://s.taobao.com/list","class":"em"},{"title":"取暖器","href":"http://s.taobao.com/list","class":""},{"title":"挂烫机","href":"http://s.taobao.com/list","class":""},{"title":"个护电器","href":"http://www.taobao.com/market/jiadian/gh.php","class":""},{"title":"秋季补水","href":"http://s.taobao.com/list","class":"em"},{"title":"剃须刀","href":"http://s.taobao.com/list","class":""},{"title":"美容仪","href":"http://s.taobao.com/list","class":""},{"title":"美发神器","href":"http://s.taobao.com/list","class":""},{"title":"电动牙刷","href":"http://s.taobao.com/list","class":""},{"title":"电吹风","href":"http://s.taobao.com/list","class":""},{"title":"办公耗材","href":"http://www.taobao.com/market/jiadian/office.php","class":""},{"title":"投影仪","href":"http://s.taobao.com/list","class":""},{"title":"打印机","href":"http://s.taobao.com/list","class":"em"},{"title":"A4纸","href":"http://s.taobao.com/list","class":""},{"title":"办公一体机","href":"http://s.taobao.com/list","class":""}],"type2":[],"type3":[{"title":"厨房家电","href":"http://s.taobao.com/list","class":"guess "},{"title":"烤箱","href":"http://s.taobao.com/list","class":"em"},{"title":"家用电器","href":"http://s.taobao.com/list","class":""},{"title":"暖风机","href":"http://s.taobao.com/list","class":"em"},{"title":"液晶","href":"http://s.taobao.com/list","class":""},{"title":"卷发器","href":"http://s.taobao.com/list","class":""},{"title":"电热水壶","href":"http://s.taobao.com/list","class":""},{"title":"迷你洗衣机","href":"http://s.taobao.com/list","class":""},{"title":"吹风机","href":"http://s.taobao.com/list","class":""},{"title":"电动剃须刀","href":"http://s.taobao.com/list","class":""}]} ,
		cata7: {"header":{"index1":{"title":"护肤彩妆","href":"http://www.taobao.com/market/mei/index.php","class":""},"index2":{"title":"冬日不做女旱子","href":"http://miiee.taobao.com/themes/theme_406.htm","class":""},"index3":{"title":"男士护肤","href":"http://www.taobao.com/market/mei/nan2014.php","class":""},"index4":{"title":"真人试用","href":"http://riji.taobao.com/mei/list.htm","class":""}},"type1":[{"title":"美容护肤","href":"http://www.taobao.com/market/mei/hufu2014.php","class":""},{"title":"卸妆","href":"http://s.taobao.com/list","class":""},{"title":"洁面","href":"http://s.taobao.com/list","class":""},{"title":"爽肤水","href":"http://s.taobao.com/list","class":""},{"title":"芦荟胶","href":"http://s.taobao.com/list","class":"em"},{"title":"眼霜","href":"http://s.taobao.com/list","class":""},{"title":"强效保养","href":"http://spu.taobao.com/spu/spulist.htm","class":""},{"title":"精华","href":"http://s.taobao.com/list","class":""},{"title":"面膜","href":"http://s.taobao.com/list","class":""},{"title":"套装","href":"http://s.taobao.com/list","class":""},{"title":"身体乳","href":"http://s.taobao.com/list","class":""},{"title":"手霜","href":"http://s.taobao.com/list","class":"em"},{"title":"润唇膏","href":"http://s.taobao.com/list","class":""},{"title":"超值彩妆","href":"http://www.taobao.com/market/mei/cai2014.php","class":""},{"title":"眼线","href":"http://s.taobao.com/list","class":""},{"title":"彩妆盘","href":"http://s.taobao.com/list","class":""},{"title":"BB霜","href":"http://s.taobao.com/list","class":"em"},{"title":"粉底液","href":"http://s.taobao.com/list","class":""},{"title":"唇膏","href":"http://s.taobao.com/list","class":""},{"title":"换季保养","href":"http://www.taobao.com/market/mei/huanji.php","class":"em"},{"title":"瘦身","href":"http://s.taobao.com/list","class":"em"},{"title":"脱毛","href":"http://s.taobao.com/list","class":""},{"title":"丰胸","href":"http://s.taobao.com/list","class":""},{"title":"收缩毛孔","href":"http://s.taobao.com/list","class":""},{"title":"去黑头","href":"http://s.taobao.com/list","class":""},{"title":"香港直发","href":"http://www.taobao.com/market/mei/haitao.php","class":""},{"title":"V脸","href":"http://s.taobao.com/list","class":""},{"title":"美白","href":"http://s.taobao.com/list","class":"em"},{"title":"去黑眼圈","href":"http://s.taobao.com/list","class":""},{"title":"祛斑","href":"http://s.taobao.com/list","class":""},{"title":"祛痘","href":"http://s.taobao.com/list","class":""}],"type2":[],"type3":[{"title":"护肤美容","href":"http://s.taobao.com/list","class":"guess "},{"title":"蚕丝面膜","href":"http://s.taobao.com/list","class":"em"},{"title":"化妆品","href":"http://s.taobao.com/list","class":""},{"title":"马油","href":"http://s.taobao.com/list","class":""},{"title":"口红","href":"http://s.taobao.com/list","class":""},{"title":"化妆水","href":"http://s.taobao.com/list","class":""},{"title":"气垫","href":"http://s.taobao.com/list","class":"em"},{"title":"洗面奶","href":"http://s.taobao.com/list","class":""},{"title":"原液","href":"http://s.taobao.com/list","class":""}]} ,
		cata8: {"header":{"index1":{"title":"母婴用品","href":"http://www.taobao.com/go/market/baobao/2014/index.php","class":""},"index2":{"title":"过年必备大牌童装","href":"http://www.taobao.com/market/baobao/tongzhuangindex.php","class":""},"index3":{"title":"玩具大礼包","href":"http://s.taobao.com/list","class":""},"index4":{"title":"淘金币活动","href":"http://www.taobao.com/market/baobao/happynewyear.php","class":""}},"type1":[{"title":"秋冬童装","href":"http://www.taobao.com/market/baobao/tongzhuangindex.php","class":"em"},{"title":"羽绒","href":"http://s.taobao.com/list","class":"em"},{"title":"棉服","href":"http://s.taobao.com/list","class":""},{"title":"毛衣","href":"http://s.taobao.com/list","class":""},{"title":"爬服","href":"http://s.taobao.com/list","class":""},{"title":"打底","href":"http://s.taobao.com/list","class":""},{"title":"棉裤","href":"http://s.taobao.com/list","class":""},{"title":"孕产用品","href":"http://www.taobao.com/market/baobao/xifen/yunchanfu/index.php","class":""},{"title":"打底裤","href":"http://s.taobao.com/list","class":""},{"title":"护腰枕","href":"http://s.taobao.com/list","class":""},{"title":"连衣裙","href":"http://s.taobao.com/list","class":""},{"title":"哺乳衣","href":"http://s.taobao.com/list","class":"em"},{"title":"毛衣","href":"http://s.taobao.com/list","class":""},{"title":"婴幼用品","href":"http://www.taobao.com/go/market/baobao/yongping2014/index.php","class":"em"},{"title":"纸尿裤","href":"http://s.taobao.com/list","class":""},{"title":"腰凳","href":"http://s.taobao.com/list","class":""},{"title":"吸盘碗","href":"http://s.taobao.com/list","class":""},{"title":"罩衣","href":"http://s.taobao.com/list","class":"em"},{"title":"浴巾","href":"http://s.taobao.com/list","class":""},{"title":"勺","href":"http://s.taobao.com/list","class":""},{"title":"婴儿营养","href":"http://s.taobao.com/list","class":""},{"title":"奶粉","href":"http://s.taobao.com/list","class":""},{"title":"豆奶","href":"http://s.taobao.com/list","class":"em"},{"title":"零食","href":"http://s.taobao.com/list","class":""},{"title":"饼干","href":"http://s.taobao.com/list","class":""},{"title":"维生素","href":"http://s.taobao.com/list","class":""},{"title":"面条","href":"http://s.taobao.com/list","class":""},{"title":"儿童玩具","href":"http://www.taobao.com/market/baobao/wanjushichang.php","class":""},{"title":"新年玩具","href":"http://s.taobao.com/list","class":"em"},{"title":"电动车","href":"http://s.taobao.com/list","class":""},{"title":"毛绒","href":"http://s.taobao.com/list","class":""},{"title":"遥控","href":"http://s.taobao.com/list","class":""},{"title":"积木","href":"http://s.taobao.com/list","class":""}],"type2":[],"type3":[{"title":"童装棉服","href":"http://s.taobao.com/list","class":"guess "},{"title":"打底裤","href":"http://s.taobao.com/list","class":"em"},{"title":"棉衣","href":"http://s.taobao.com/list","class":""},{"title":"儿童羽绒服","href":"http://s.taobao.com/list","class":"em"},{"title":"靴子","href":"http://s.taobao.com/list","class":""},{"title":"女童毛衣","href":"http://s.taobao.com/list","class":""},{"title":"公仔","href":"http://s.taobao.com/list","class":""},{"title":"连衣裙","href":"http://s.taobao.com/list","class":""},{"title":"普通外套","href":"http://s.taobao.com/list","class":""},{"title":"童鞋","href":"http://s.taobao.com/list","class":""}]},
		cata9: {"header":{"index1":{"title":"家居家纺","href":"http://www.taobao.com/market/home/2014/index.php","class":""},"index2":{"title":"清仓扫货 马上抢","href":"http://www.taobao.com/market/home/qingcang.php","class":""},"index3":{"title":"大牌床品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},"index4":{"title":"家具风尚","href":"http://www.taobao.com/market/home/jiajushichang.php","class":""}},"type1":[{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"床上用品","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"四件套","href":"http://s.taobao.com/search","class":"em"},{"title":"蚕丝被","href":"http://s.taobao.com/list","class":""},{"title":"羽绒被","href":"http://s.taobao.com/list","class":""},{"title":"颈椎枕","href":"http://s.taobao.com/list","class":""},{"title":"毛毯","href":"http://s.taobao.com/list","class":""},{"title":"布艺缝纫","href":"http://www.taobao.com/market/home/jiafangshichang.php","class":""},{"title":"钻石绣","href":"http://s.taobao.com/list","class":""},{"title":"沙发垫","href":"http://s.taobao.com/list","class":""},{"title":"窗帘","href":"http://s.taobao.com/list","class":"em"},{"title":"靠垫被","href":"http://s.taobao.com/list","class":""},{"title":"地毯","href":"http://s.taobao.com/list","class":""},{"title":"坐垫","href":"http://s.taobao.com/list","class":""},{"title":"客厅家具","href":"http://www.taobao.com/market/home/jiajushichang.php","class":""},{"title":"沙发","href":"http://www.taobao.com/market/home/citiao/shafalei.php","class":"em"},{"title":"茶几","href":"http://www.taobao.com/market/home/citiao/chaji.php","class":""},{"title":"电视柜","href":"http://www.taobao.com/market/home/citiao/dianshiju.php","class":""},{"title":"懒人沙发","href":"http://www.taobao.com/market/home/citiao/lanrenshafa.php","class":""},{"title":"鞋柜","href":"http://www.taobao.com/market/home/citiao/xieju.php","class":""},{"title":"餐桌椅","href":"http://www.taobao.com/market/home/citiao/canzhuo.php","class":""},{"title":"卧室家具","href":"http://www.taobao.com/market/home/jiajushichang.php","class":""},{"title":"床","href":"http://www.taobao.com/market/home/citiao/chuang.php","class":""},{"title":"衣柜","href":"http://www.taobao.com/market/home/citiao/yiju.php","class":"em"},{"title":"书柜","href":"http://www.taobao.com/market/home/citiao/shuju.php","class":""},{"title":"电脑桌","href":"http://www.taobao.com/market/home/citiao/diannaozhuo.php","class":""},{"title":"高低床","href":"http://www.taobao.com/market/home/citiao/gaodichuang.php","class":""},{"title":"架类","href":"http://www.taobao.com/market/home/citiao/geban.php","class":""},{"title":"家居饰品","href":"http://www.taobao.com/market/home/home-decoration.php","class":""},{"title":"摆件","href":"http://s.taobao.com/list","class":""},{"title":"画","href":"http://s.taobao.com/list","class":""},{"title":"照片墙","href":"http://s.taobao.com/list","class":""},{"title":"花艺","href":"http://s.taobao.com/list","class":""},{"title":"挂钟","href":"http://s.taobao.com/list","class":"em"},{"title":"壁饰","href":"http://s.taobao.com/list","class":""}],"type2":[],"type3":[{"title":"床上用品","href":"http://s.taobao.com/list","class":"guess "},{"title":"毛巾","href":"http://s.taobao.com/list","class":"em"},{"title":"住宅家具","href":"http://s.taobao.com/list","class":""},{"title":"四件套","href":"http://s.taobao.com/list","class":"em"},{"title":"礼物","href":"http://s.taobao.com/list","class":""},{"title":"十字绣","href":"http://s.taobao.com/list","class":""},{"title":"被子","href":"http://s.taobao.com/list","class":"em"},{"title":"立体墙贴","href":"http://s.taobao.com/list","class":""},{"title":"家居拖鞋","href":"http://s.taobao.com/list","class":""},{"title":"沙发套","href":"http://s.taobao.com/list","class":""}]} ,
		cata10: {"header":{"index1":{"title":"家装建材","href":"http://jia.taobao.com","class":""},"index2":{"title":"家装总有适合你","href":"http://jia.taobao.com","class":""},"index3":{"title":"设计十强","href":"http://www.taobao.com/market/jia/snsjdssq.php","class":""},"index4":{"title":"家装日记","href":"http://youjia.taobao.com/yjriji/diarylist.htm","class":""}},"type1":[{"title":"卫浴工程","href":"http://www.taobao.com/market/jia/weiyu.php","class":"em"},{"title":"浴室柜","href":"http://s.taobao.com/list","class":""},{"title":"马桶","href":"http://s.taobao.com/list","class":""},{"title":"花洒套餐","href":"http://s.taobao.com/list","class":""},{"title":"水龙头","href":"http://s.taobao.com/list","class":""},{"title":"水槽","href":"http://s.taobao.com/list","class":""},{"title":"浴霸","href":"http://s.taobao.com/list","class":""},{"title":"照明工程","href":"http://www.taobao.com/market/jia/zhaoming.php","class":""},{"title":"吊灯","href":"http://s.taobao.com/list","class":""},{"title":"吸顶灯","href":"http://s.taobao.com/list","class":""},{"title":"射灯","href":"http://s.taobao.com/list","class":""},{"title":"台灯","href":"http://s.taobao.com/list","class":""},{"title":"壁灯","href":"http://s.taobao.com/list","class":""},{"title":"室外灯","href":"http://s.taobao.com/list","class":""},{"title":"墙地面","href":"http://www.taobao.com/market/jia/qiangmian.php","class":""},{"title":"室内门","href":"http://s.taobao.com/list","class":""},{"title":"涂料","href":"http://s.taobao.com/list","class":""},{"title":"地板","href":"http://s.taobao.com/list","class":""},{"title":"墙纸","href":"http://s.taobao.com/list","class":""},{"title":"马赛克","href":"http://s.taobao.com/list","class":""},{"title":"瓷砖","href":"http://s.taobao.com/list","class":""},{"title":"水电工程","href":"http://www.taobao.com/market/jia/shuidian.php","class":""},{"title":"门锁","href":"http://s.taobao.com/list","class":""},{"title":"电钻","href":"http://s.taobao.com/list","class":""},{"title":"开关","href":"http://s.taobao.com/list","class":""},{"title":"插座","href":"http://s.taobao.com/list","class":""},{"title":"摄像头","href":"http://s.taobao.com/list","class":""},{"title":"工具箱","href":"http://s.taobao.com/list","class":""},{"title":"设计施工","href":"http://s.taobao.com/list","class":""},{"title":"效果图","href":"http://s.taobao.com/search","class":""},{"title":"施工图","href":"http://s.taobao.com/search","class":"em"},{"title":"施工","href":"http://s.taobao.com/search","class":""},{"title":"监理","href":"http://s.taobao.com/search","class":""},{"title":"全包","href":"http://s.taobao.com/search","class":""}],"type2":[],"type3":[{"title":"家装主材","href":"http://s.taobao.com/list","class":"guess "},{"title":"节能灯","href":"http://s.taobao.com/list","class":"em"},{"title":"灯泡","href":"http://s.taobao.com/list","class":""},{"title":"客厅灯","href":"http://s.taobao.com/list","class":"em"},{"title":"壁纸","href":"http://s.taobao.com/list","class":""},{"title":"装饰台灯","href":"http://s.taobao.com/list","class":""},{"title":"花洒","href":"http://s.taobao.com/list","class":"em"},{"title":"洗脸盆","href":"http://s.taobao.com/list","class":""},{"title":"led台灯","href":"http://s.taobao.com/list","class":""},{"title":"水晶吊灯","href":"http://s.taobao.com/list","class":""}]} ,
		cata11: {},
		cata12: {"header":{"index1":{"title":"百货市场","href":"http://baihuo.taobao.com/","class":""},"index2":{"title":"清仓啦！1件不留","href":"http://www.taobao.com/market/home/qingcang.php","class":""},"index3":{"title":"洗护纸品","href":"http://www.taobao.com/market/baihuo/xihubeauty.php","class":""},"index4":{"title":"收纳整理","href":"http://www.taobao.com/market/baihuo/zlsn.php","class":""}},"type1":[{"title":"居家保暖","href":"http://www.taobao.com/market/baihuo/newintimebaihuo.php","class":""},{"title":"保暖品","href":"http://s.taobao.com/list","class":"em"},{"title":"天堂伞","href":"http://www.taobao.com/market/baihuo/citiao/2014/index/san.php","class":""},{"title":"口罩","href":"http://s.taobao.com/list","class":""},{"title":"热水袋","href":"http://s.taobao.com/list","class":"em"},{"title":"棉拖鞋","href":"http://s.taobao.com/list","class":"em"},{"title":"厨房餐饮","href":"http://www.taobao.com/market/baihuo/womencookingclub.php","class":"em"},{"title":"玻璃杯","href":"http://www.taobao.com/market/baihuo/citiao/bolibei.php","class":""},{"title":"保温杯","href":"http://s.taobao.com/list","class":""},{"title":"茶具","href":"http://www.taobao.com/market/baihuo/citiao/2014/index/chajutaozu.php","class":"em"},{"title":"炒锅","href":"http://s.taobao.com/list","class":""},{"title":"餐具","href":"http://s.taobao.com/list","class":""},{"title":"碗","href":"http://s.taobao.com/list","class":""},{"title":"洗护纸品","href":"http://www.taobao.com/market/baihuo/xihubeauty.php","class":""},{"title":"牙膏","href":"http://s.taobao.com/list","class":""},{"title":"洗发水","href":"http://s.taobao.com/list","class":"em"},{"title":"卫生巾","href":"http://s.taobao.com/list","class":""},{"title":"沐浴液","href":"http://s.taobao.com/list","class":""},{"title":"洗衣液","href":"http://s.taobao.com/list","class":"em"},{"title":"居家日用","href":"http://www.taobao.com/market/baihuo/newintimebaihuo.php","class":""},{"title":"创意品","href":"http://www.taobao.com/market/baihuo/citiao/2014/index/chuangyilipin.php","class":"em"},{"title":"喜糖盒","href":"http://s.taobao.com/list","class":""},{"title":"眼罩","href":"http://s.taobao.com/list","class":"em"},{"title":"缝纫机","href":"http://s.taobao.com/list","class":""},{"title":"相册","href":"http://s.taobao.com/list","class":""},{"title":"时钟","href":"http://s.taobao.com/list","class":""},{"title":"整理收纳","href":"http://www.taobao.com/market/baihuo/zlsn.php","class":""},{"title":"收纳箱","href":"http://s.taobao.com/list","class":"em"},{"title":"晾衣架","href":"http://s.taobao.com/list","class":""},{"title":"鞋柜","href":"http://s.taobao.com/list","class":""},{"title":"压缩袋","href":"http://s.taobao.com/list","class":""},{"title":"收纳盒","href":"http://s.taobao.com/list","class":""},{"title":"家庭清洁","href":"http://www.taobao.com/market/baihuo/jiatingqingjie/2014.php","class":""},{"title":"拖把","href":"http://s.taobao.com/list","class":"em"},{"title":"垃圾桶","href":"http://s.taobao.com/list","class":""},{"title":"洗脸刷","href":"http://s.taobao.com/list","class":""},{"title":"干发","href":"http://s.taobao.com/list","class":""},{"title":"节庆用品","href":"http://www.taobao.com/market/baihuo/festivalwedding2014.php","class":""},{"title":"情人节","href":"http://s.taobao.com/list","class":""},{"title":"结婚吧","href":"http://www.taobao.com/market/baihuo/festivalwedding2014.php","class":""},{"title":"送礼","href":"http://s.taobao.com/list","class":""}],"type2":[],"type3":[]}, 
		cata13: {"header":{"index1":{"title":"汽车摩托","href":"http://www.taobao.com/market/car/index.php","class":""},"index2":{"title":"测测你的车值多少钱","href":"http://www.taobao.com/market/car/usedcar.php","class":""},"index3":{"title":"保暖座垫","href":"http://s.taobao.com/list","class":""},"index4":{"title":"夜视记录仪","href":"http://s.taobao.com/list","class":""}},"type1":[{"title":"内饰外饰","href":"http://www.taobao.com/market/car/nsws.php","class":"em"},{"title":"座垫","href":"http://s.taobao.com/list","class":""},{"title":"汽车香水","href":"http://s.taobao.com/list","class":""},{"title":"脚垫","href":"http://s.taobao.com/list","class":""},{"title":"车衣","href":"http://s.taobao.com/list","class":""},{"title":"车有宝宝","href":"http://s.taobao.com/list","class":"em"},{"title":"汽车配件","href":"http://www.taobao.com/market/car/pjsj.php","class":""},{"title":"氙气灯","href":"http://s.taobao.com/list","class":""},{"title":"轮胎","href":"http://s.taobao.com/list","class":""},{"title":"雨刮","href":"http://s.taobao.com/search","class":"em"},{"title":"防追尾","href":"http://s.taobao.com/list","class":""},{"title":"改装包围","href":"http://s.taobao.com/list","class":""},{"title":"电子影音","href":"http://www.taobao.com/market/car/dzyy.php","class":""},{"title":"记录仪","href":"http://s.taobao.com/list","class":""},{"title":"净化器","href":"http://s.taobao.com/list","class":""},{"title":"汽车音响","href":"http://s.taobao.com/list","class":""},{"title":"电子狗","href":"http://s.taobao.com/list","class":"em"},{"title":"导航","href":"http://s.taobao.com/list","class":""},{"title":"摩托电动","href":"http://www.taobao.com/market/car/ddcpd.php","class":""},{"title":"挡风被","href":"http://www.taobao.com/go/market/car/lianglunche.php#xyb2","class":""},{"title":"飞行器","href":"http://s.taobao.com/list","class":"em"},{"title":"代步车","href":"http://s.taobao.com/list","class":""},{"title":"儿童电动车","href":"http://s.taobao.com/list","class":""},{"title":"汽车服务","href":"http://www.taobao.com/market/car/qcfw.php","class":""},{"title":"洗车卡","href":"http://www.taobao.com/market/car/chebang.php#main6","class":""},{"title":"爱车估价","href":"http://www.taobao.com/market/car/usedcar.php","class":"em"},{"title":"保养","href":"http://www.taobao.com/market/car/qcfw.php#guid-1412064076588","class":""},{"title":"镀晶","href":"http://s.taobao.com/list","class":""},{"title":"二手车","href":"http://www.taobao.com/market/car/chebang.php#main5","class":""}],"type2":[],"type3":[{"title":"汽车用品","href":"http://s.taobao.com/list","class":"guess "},{"title":"坐垫","href":"http://s.taobao.com/list","class":"em"},{"title":"行车记录仪","href":"http://s.taobao.com/list","class":""},{"title":"汽车脚垫","href":"http://s.taobao.com/list","class":"em"},{"title":"车贴","href":"http://s.taobao.com/list","class":""},{"title":"座套","href":"http://s.taobao.com/list","class":""},{"title":"车外灯","href":"http://s.taobao.com/list","class":""},{"title":"车用香水","href":"http://s.taobao.com/list","class":""},{"title":"方向盘套","href":"http://s.taobao.com/list","class":""},{"title":"车挂","href":"http://s.taobao.com/list","class":""}]} ,
		cata14: {"header":{"index1":{"title":"花鸟文娱","href":"http://enjoy.taobao.com/","class":""},"index2":{"title":"宠物完美过冬","href":"http://s.taobao.com/list","class":""},"index3":{"title":"新年特别款","href":"http://www.taobao.com/market/xianhua/flower.php","class":""},"index4":{"title":"日记红人大赛","href":"http://riji.taobao.com/pet/list.htm","class":""}},"type1":[{"title":"绿植园艺","href":"http://www.taobao.com/market/xianhua/xianhuayuanyi.php","class":""},{"title":"阳台花卉","href":"http://s.taobao.com/list","class":"em"},{"title":"绿植","href":"http://www.taobao.com/market/xianhua/citiao/minizhiwu.php","class":""},{"title":"花盆","href":"http://s.taobao.com/list","class":""},{"title":"花架","href":"http://s.taobao.com/list","class":""},{"title":"奇趣植物","href":"http://s.taobao.com/list","class":""},{"title":"鲜花花卉","href":"http://www.taobao.com/market/xianhua/flower.php","class":""},{"title":"鲜花","href":"http://s.taobao.com/list","class":"em"},{"title":"花卉盆栽","href":"http://www.taobao.com/market/xianhua/plant.php","class":""},{"title":"多肉","href":"http://s.taobao.com/list","class":""},{"title":"园艺用品","href":"http://www.taobao.com/market/xianhua/hyjs.php","class":""},{"title":"仿真花","href":"http://www.taobao.com/market/2014/1212/trade/xianhuayuanyi.php","class":""},{"title":"猫狗世界","href":"http://www.taobao.com/market/pet/maogou.php","class":""},{"title":"狗狗","href":"http://s.taobao.com/list","class":""},{"title":"猫咪","href":"http://s.taobao.com/list","class":""},{"title":"粮食","href":"http://s.taobao.com/list","class":""},{"title":"日用品","href":"http://s.taobao.com/list","class":""},{"title":"保暖窝","href":"http://s.taobao.com/list","class":"em"},{"title":"棉服","href":"http://s.taobao.com/list","class":""},{"title":"水族世界","href":"http://www.taobao.com/market/pet/shuizu.php","class":""},{"title":"鱼","href":"http://s.taobao.com/list","class":""},{"title":"水族箱","href":"http://s.taobao.com/list","class":"em"},{"title":"过滤","href":"http://s.taobao.com/list","class":""},{"title":"小宠必备","href":"http://s.taobao.com/list","class":""},{"title":"鸟类","href":"http://s.taobao.com/list","class":""},{"title":"图书乐器","href":"http://www.taobao.com/market/wenyu/wenyu.php","class":""},{"title":"儿童读物","href":"http://s.taobao.com/list","class":"em"},{"title":"音像","href":"http://www.taobao.com/market/wenyu/music.php","class":""},{"title":"CD","href":"http://s.taobao.com/list","class":""},{"title":"个性定制","href":"http://www.taobao.com/market/wenyu/diy.php","class":""},{"title":"钢琴","href":"http://s.taobao.com/list","class":""},{"title":"吉他","href":"http://s.taobao.com/list","class":""}],"type2":[],"type3":[{"title":"宠物用品","href":"http://s.taobao.com/list","class":"guess "},{"title":"盆栽","href":"http://s.taobao.com/list","class":"em"},{"title":"衣服","href":"http://s.taobao.com/list","class":""},{"title":"陶瓷花盆","href":"http://s.taobao.com/list","class":"em"},{"title":"种子","href":"http://s.taobao.com/list","class":""},{"title":"花卉","href":"http://s.taobao.com/list","class":""},{"title":"永生花","href":"http://s.taobao.com/list","class":""},{"title":"犬主粮","href":"http://s.taobao.com/list","class":""},{"title":"礼盒","href":"http://s.taobao.com/list","class":""},{"title":"水族箱","href":"http://s.taobao.com/list","class":""}]},
		cata15: {"header":{"index1":{"title":"生活服务","href":"http://life.taobao.com/market/life/index_2014.php","class":""},"index2":{"title":"年底洗车","href":"http://s.taobao.com/list","class":""},"index3":{"title":"风水大师","href":"http://xue.taobao.com/market/xue/dzfs.php","class":""},"index4":{"title":"爆款抢购","href":"http://www.taobao.com/market/2014/1212/life.php","class":""}},"type1":[{"title":"万能缴费","href":"http://life.taobao.com/go/act/bendi/bianmin.php","class":"em"},{"title":"话费","href":"http://life.taobao.com/market/life/czk.php","class":"em"},{"title":"水电煤","href":"http://life.taobao.com/market/sdmjf2011.php","class":""},{"title":"交罚单","href":"http://life.taobao.com/market/jtfk.php","class":""},{"title":"宽带费","href":"http://life.taobao.com/market/guhkd2011.php","class":""},{"title":"加油卡","href":"http://life.taobao.com/market/jyk2012.php","class":""},{"title":"便民服务","href":"http://life.taobao.com","class":""},{"title":"汽车服务","href":"http://s.taobao.com/list","class":""},{"title":"洗衣","href":"http://s.taobao.com/list","class":""},{"title":"找兼职","href":"http://life.taobao.com/market/bendi/job.php","class":""},{"title":"宠物","href":"http://s.taobao.com/list","class":""},{"title":"钟点工","href":"http://1.life.taobao.com/hourlyEmp/fwAppoint.htm","class":"em"},{"title":"最家生活","href":"http://life.taobao.com/","class":"em"},{"title":"月嫂","href":"http://s.taobao.com/list","class":""},{"title":"洗车","href":"http://s.taobao.com/list","class":""},{"title":"私人厨师","href":"http://s.taobao.com/search","class":"em"},{"title":"KTV","href":"http://ktv.taobao.com","class":""},{"title":"婚纱摄影","href":"http://hunban.taobao.com/","class":""},{"title":"洗油烟机","href":"http://life.taobao.com/market/life/zjfw-w.php","class":""},{"title":"教育培训","href":"http://xue.taobao.com/","class":""},{"title":"涨工资","href":"http://i.xue.taobao.com/list.htm","class":""},{"title":"团购","href":"http://ju.taobao.com/jusp/tbtongxue/tp.htm","class":""},{"title":"女神","href":"http://xue.taobao.com/market/xue/girlxy.php","class":""},{"title":"风水","href":"http://xue.taobao.com/market/xue/dzfs.php","class":"em"},{"title":"无码直播","href":"http://xue.taobao.com/market/xue/tbtx_zhiboye.php#tbtx","class":""},{"title":"买房租房","href":"http://fang.taobao.com/","class":""},{"title":"新房","href":"http://fang.taobao.com/buildingList.htm","class":""},{"title":"租房","href":"http://fang.taobao.com/rentalList.htm","class":""},{"title":"二手房","href":"http://fang.taobao.com/resoldList.htm","class":""},{"title":"家装红包","href":"http://fang.taobao.com/","class":""},{"title":"精品房产","href":"http://fang.taobao.com/","class":""}],"type2":[],"type3":[{"title":"话费充值","href":"http://s.taobao.com/list","class":"guess "},{"title":"充值卡","href":"http://s.taobao.com/list","class":"em"},{"title":"直充","href":"http://s.taobao.com/list","class":"em"},{"title":"电信手机","href":"http://s.taobao.com/list","class":""},{"title":"手机卡","href":"http://s.taobao.com/list","class":""},{"title":"wifi","href":"http://s.taobao.com/list","class":""},{"title":"IP电话卡","href":"http://s.taobao.com/list","class":""}]} ,
		cata16: {"header":{"index1":{"title":"手机流量免费送！要么？","href":"http://www.taobao.com/market/game/songll.php","class":""},"index2":{"title":"篮球NBA","href":"http://caipiao.taobao.com/lottery/order/lottery_jclq_hhgg.htm","class":""},"index3":{"title":"大神买彩","href":"http://caipiao.taobao.com/lottery/order/united_reds.htm","class":""}},"type1":[{"title":"游戏","href":"http://game.taobao.com/","class":""},{"title":"免费游戏","href":"http://wan.taobao.com/","class":"em"},{"title":"点卡","href":"http://www.taobao.com/market/game/chl-card.php","class":""},{"title":"游戏币","href":"http://www.taobao.com/market/game/djdq.php","class":""},{"title":"装备","href":"http://www.taobao.com/market/game/zbdq.php","class":""},{"title":"代练","href":"http://www.taobao.com/market/game/dailian.php","class":""},{"title":"账号","href":"http://www.taobao.com/market/game/zhdq.php","class":""},{"title":"彩票","href":"http://caipiao.taobao.com/","class":"em"},{"title":"双色球","href":"http://caipiao.taobao.com/lottery/order/lottery_ssq.htm","class":""},{"title":"大乐透","href":"http://caipiao.taobao.com/lottery/order/lottery_dlt.htm","class":""},{"title":"足彩","href":"http://caipiao.taobao.com/lottery/order/lottery_jczq_hhgg_by_client.htm","class":"em"},{"title":"快3","href":"http://caipiao.taobao.com/lottery/order/lottery_k3.htm","class":""},{"title":"送彩票","href":"http://www.taobao.com/go/act/lottery/caitttdf.php","class":""},{"title":"闲鱼","href":"http://www.taobao.com/market/2/xianyu1214.php","class":"em"},{"title":"苹果","href":"http://s.2.taobao.com/list/list.htm","class":""},{"title":"电脑","href":"http://s.2.taobao.com/list/list.htm","class":""},{"title":"三星","href":"http://s.2.taobao.com/list/list.htm","class":""},{"title":"二手车","href":"http://s.taobao.com/search","class":"em"},{"title":"10元漫画书","href":"http://s.2.taobao.com/list/theme.htm","class":""},{"title":"土特产","href":"http://s.2.taobao.com/list/list.htm","class":"em"},{"title":"二手镜头","href":"http://s.2.taobao.com/list/theme.htm","class":""},{"title":"高跟鞋","href":"http://s.2.taobao.com/list/theme.htm","class":""},{"title":"海贼王","href":"http://s.2.taobao.com/list/theme.htm","class":""},{"title":"萌物","href":"http://s.2.taobao.com/list/theme.htm","class":"em"},{"title":"达人精选","href":"http://daren.taobao.com/","class":""},{"title":"爱家好物","href":"http://www.taobao.com/market/2014/99/uz.php","class":""},{"title":"气质风衣","href":"http://shi.taobao.com/market/shi/fengyi.php","class":""},{"title":"眼部护理","href":"http://shi.taobao.com/market/shi/yanbuhuli.php","class":""},{"title":"马克杯","href":"http://shi.taobao.com/market/shi/beizimen.php","class":""}],"type2":[],"type3":[{"title":"爱逛街","href":"http://guang.taobao.com/","class":"guess "},{"title":"毛领大衣","href":"http://guang.taobao.com/activity/index.htm","class":""},{"title":"画眼线","href":"http://guang.taobao.com/street/girlList.htm","class":""},{"title":"雪地靴","href":"http://guang.taobao.com/activity/index.htm","class":""},{"title":"9.9百货","href":"http://guang.taobao.com/activity/index.htm","class":""},{"title":"韩版","href":"http://guang.taobao.com/street/girlList.htm","class":""}]},

	};	
	define(function() {
		var data = {
			catas: catas
		};
		return data;
	});
})();